image: ubuntu

before_script:
  - apt-get -qq update -y && apt-get -qq upgrade -y
  - apt-get -qq install -y python3-virtualenv build-essential

mytestrunner:
  script:
    - make init
    - make install
    - make test
