language: python
python:
  - '3.6'
install: pip install pipenv && apt-get install -y g++
stages:
  - test
jobs:
  include:
    - stage: test
      name: Run local tests
      script: make init && make install && make test
