language: python
python:
  - '3.6'
install: pip install pipenv
stages:
  - test
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8
jobs:
  include:
    - stage: test
      name: Run local tests
      script: g++ --version && make init && make install && make test
