language: python
python:
  - '3.6'
install: pip install pipenv
stages:
  - test
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
jobs:
  include:
    - stage: test
      name: Run local tests
      script: make init && make install && make test
