language: python
python:
  - '3.6'
install: pip install pipenv
stages:
  - test
addons:
  apt:
    packages:
      - gcc
      - g++
jobs:
  include:
    - stage: test
      name: Run local tests
      script: make init && make install && make test
